### ISSUE TITLE
Help with running this

### ISSUE THREAD

**Issue by markgyoni** [seriousm4x/discord-developer-badge#1]
Hi,

How can I run this(preferably on debian)? The files have no extensions.

Thanks

**Comment by seriousm4x** [comment]
- download the [linux version](https://github.com/seriousm4x/discord-developer-badge/releases/download/v1.0.0/devbadge-linux-amd64)
- `chmod +x devbadge-linux-amd64`
- `./devbadge-linux-amd64 -t <token>`

**Comment by markgyoni** [comment]
Oh, I didn't realize it was that easy. It worked, thanks!

**Comment by seriousm4x** [comment]
you're welcome 😄
